### ISSUE TITLE
shell on macos has a problem?

### ISSUE THREAD

**Issue by juzeon** [RoosterDragon/Desktop-Ponies#21]
After installing the latest mono on osx(el capitan) and running the shell `RunOnMac.command`, the console showed an error like `exec: mono: not found`.I changed the line 4 into `exec /Library/Frameworks/Mono.framework/Commands/mono32 "Desktop Ponies.exe" "$@"` and the it worked properly. Is it an problem?

**Comment by RoosterDragon** [comment]
This might be due to recent changes requiring you to run `mono32` instead of `mono`.

Sounds like your change will work for you. It would be nice if the `RunOnMac.command` could check which of `mono32` and `mono` existed and use the one that did, but I'm not familiar enough to with bash to know how to state such a thing.

**Comment by RoosterDragon** [comment]
Fixed by #22.
