### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by StevenGann** [RoosterDragon/Desktop-Ponies#6]
I am interested in helping with Desktop Ponies. I've used it for a long time but haven't seen any major improvements. Of course, I never realized it was on Github either.

I have extensive experience with C#, and some with VB.NET. I cannot do art, but I can code. What can I help with?

**Comment by RoosterDragon** [comment]
Hi,

You're welcome to submit a PR for whatever you like really. If you're looking for suggestions I might suggest looking at the ponychan thread for any bug reports or feature requests that occasionally get suggested there. Otherwise, a few things I can think of are:
- The UI isn't that great in many areas - if you feel like improving/polishing it that'd be cool.
- Improving the editor to make creating and editing ponies easier would be nice.
- Several users quite like the minigames, adding a new one or improving the AI might be a neat thing to do.
- Bug fixes are extremely welcome.
